# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Basic 64bit Debian Squeeze Image
  config.vm.box = "debian"

  
  # PLEASE NOTE, you can use any debian squeeze box, if you cannot reach this URL
  config.vm.box_url = "http://files.sbrforum.priv/Installers/Vagrant/Boxes/debian/squeeze/debian-squeeze.box"

  # This is where your ruby code will live
  config.vm.synced_folder "./data", "/opt/data"
  
  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network :private_network, ip: "192.168.33.10"
  
  
  config.vm.network  :forwarded_port, guest: 3000, host: 3000
  
  # This is the magic sauce which provisions RVM, Ruby
  config.vm.provision :puppet do |puppet|
	  puppet.manifests_path = "puppet/manifests"
	  puppet.module_path    = "puppet/modules"
	  puppet.manifest_file  = "development.pp"
  end
end
